### ISSUE TITLE
[Give 2.0] UPDATE: Add Settings Export section to Export Doc

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give-Docs#101]
## NEW DOC NEEDED: 
Documentation is needed for the new Settings Importer / Exporter. This effectively allows you to migrate your global settings, including add-ons, from one site to another. 

More described on the issue here: https://github.com/WordImpress/Give/issues/2009 and within the PR here:  https://github.com/WordImpress/Give/issues/2009

@raftaar1191 created a video displaying how it works in general here (audio is rough): http://screencast-o-matic.com/watch/cb6TrYIRtv

**Comment by mathetos** [comment]
This is resolved. See the Give Export Settings info here:
https://givewp.com/documentation/core/tools/exports-tab/

And the Import Settings tool here:
https://givewp.com/documentation/core/tools/import/import-give-settings/
