### ISSUE TITLE
UPDATE: GIF and Screenshots for Give Manual Donations addons

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give-Docs#105]
ISSUE CONTENT
**URL:** https://givewp.com/addons/manual-donations/

**PROBLEM:** 
GIF's and ScreenShots of Give Manual Donations are outdated and needs update.

For Example, `New Transaction` button is now `New Donation`

**SOLUTION:** 
Update the GIF's and Screenshots with the latest version.

**Comment by Benunc** [comment]
I don't have edit capability for EDD products. assigning to @mathetos

**Comment by mathetos** [comment]
Thanks @mehul0810 -- updated all screenshots and added a section on support for recurring donations as well.
