### ISSUE TITLE
UPDATE: Include details about hidden and phone field in the FFM doc

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give-Docs#109]
ISSUE CONTENT
**URL:** https://givewp.com/documentation/add-ons/form-field-manager/understanding-the-various-form-fields/
**PROBLEM:** Include details about hidden and phone field this doc. Also update the screenshots
**SOLUTION:** We need to add details about hidden and phone field that is now available with FFM.

**Comment by samsmith89** [comment]
Added in the 2 fields. Went through all of the images and removed duplicate Caption/Alt tags.
