### ISSUE TITLE
Docs needed for new Stripe "Statement Descriptor" field

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give-Docs#111]
ISSUE CONTENT
**URL:** https://givewp.com/documentation/add-ons/stripe-gateway/

In version `1.5.1` I added a "Statement Descriptor" field:

![2017-11-29_12-24-38](https://user-images.githubusercontent.com/1571635/33397448-7e4099a2-d500-11e7-8e0f-f4e80d417d90.png)

This allows you to customize the info that displays on bank statements. By default, it will be the website name.

![2017-11-29_12-26-26](https://user-images.githubusercontent.com/1571635/33397476-964be70e-d500-11e7-9256-32cc228810b8.png)

**PROBLEM:** 
There is mention of this new feature

**Comment by samsmith89** [comment]
I have added this section to the docs at:
https://givewp.com/documentation/add-ons/stripe-gateway/

**Comment by mathetos** [comment]
@samsmith89 Thanks for doing this. Just one minor issue. Please make sure every image that we place in the article has a caption and NOT Alt Text. The new screenshot currently is missing a caption. The caption should be descriptive of what is on the screen, think of blind visitors when creating captions. It should be descriptive but not lengthy. Thanks!

**Comment by Benunc** [comment]
wait... Alt text is for vision impaired folks, not the caption. at least thats how I've been doing it.

**Comment by mathetos** [comment]
@Benunc See Slack convo here:
https://givewp.slack.com/archives/C5YD5PQ3Z/p1504910310000179

```
I just chatted with Rachel Cherry a bit about a11y and image captions. Basically, because we are outputting captions on all our docs screenshots we should either (1) NOT output an alt tag at all; or (2) Change the alt tag to something unique. I've been making the alt tags be identical to the captions and for screen-readers it ends up reading it twice in a row -- obnoxious. So from here on out please fix images when your are editing a doc and make sure when you create new ones to only output the same descriptive text for images once
```

**Comment by samsmith89** [comment]
Caption updated. Modified all duplicate Caption/Alt tags and filled out the empty ones.
