### ISSUE TITLE
Review whether we need updated Screenshots for Custom Amount Fix

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#114]
This issue may impact a lot of screenshots, but potentially negligibly. 

Review Docs in general for any glaring screenshots that REALLY need an update based on this issue:
https://github.com/WordImpress/Give/issues/2401

**Comment by marutim** [comment]
Did some screening and could only find a relevant screenshot that needed to be changed here: https://givewp.com/documentation/core/donations/

Will continue looking through other docs tomorrow

**Comment by marutim** [comment]
I screened through a lot of docs today and do not see where we can make any more changes. So assigning this to @mathetos for review.

**Comment by mathetos** [comment]
Good work Maruti. Closed!
