### ISSUE TITLE
[Give 2.0] UPDATE docs for Emails tabs

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give-Docs#118]
ISSUE CONTENT
**URL:** https://givewp.com/documentation/core/settings/emails/

**PROBLEM:** Update docs for Give 2.0 changes.

**SOLUTION:** Update the docs with latest screenshots and details explaining how all emails can be handled here. Also explaining per form email options that is introduced with Give 2.0.

**Comment by Benunc** [comment]
Started on this today. 

Made the parent document correct, and will add each type of email document tomorrow/later.

@mathetos if you want an updated call-out circle image (similar to the one on https://givewp.com/documentation/core/settings/general-settings/ for example) you need to create that image. I removed the no-longer-correct one.

**Comment by Benunc** [comment]
Update for today: overhauled https://givewp.com/documentation/core/settings/emails/the-donation-receipt-email/

**Comment by Benunc** [comment]
Update today: overhauled this one (two times, thanks to a cryptic http error!) https://givewp.com/documentation/core/settings/emails/new-donation-notification-email/

**Comment by Benunc** [comment]
Just finished https://givewp.com/documentation/core/settings/emails/new-offline-donation/
Currently working (will finish today) Offline Donation Instructions.

@samsmith89 work on:
New Donor Registration
Donor Registration

@marutim work on:
Email Access.

Note how the ones I have been working on are formatted. Make sure that the page has an `<h2>` and an `<h3>` for accessibility. Follow the format of the pages already created. Let me know if you have questions.

**Comment by Benunc** [comment]
Done with https://givewp.com/documentation/core/settings/emails/offline-donation-instructions/

Be sure when you create the docs above to make their parent doc Give Core > Emails and set the order appropriately (counting starts at 0). See the docs I just created for reference.

**Comment by marutim** [comment]
Done and published. Link: https://givewp.com/documentation/core/settings/emails/email-access/

Added the parent doc and order accordingly. 

Can someone check the content here, especially the one where Give defaults the content to Site name, Site URL or Admin email? There is no email tag in the email content and hence used square brackets to denote the same differently than the email tags. Please review and do the needful @mathetos @Benunc

**Comment by samsmith89** [comment]
Done and published with:

https://givewp.com/documentation/core/settings/emails/new-user-registration/

https://givewp.com/documentation/core/settings/emails/user-registration-information/
