### ISSUE TITLE
[Give 2.0] Update Access Control

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#120]
ISSUE CONTENT
**URL:** 
https://givewp.com/documentation/core/settings/general-settings/access-control/

**PROBLEM:**
There's a new setting called "Limit Donations Displayed". It seems simple, but it's a big change in how the donation history page works. 

**SOLUTION:** 
Add a section for "Limit Donations Displayed". Closely review this issue to understand it better, and incorporate an explanation of this setting perhaps with screenshots.
https://github.com/WordImpress/Give/issues/2023#issuecomment-337382052

It doesn't need to be a long description, just needs to have that issue as the context.

**Comment by Benunc** [comment]
done.
