### ISSUE TITLE
UPDATE: Advanced Settings Page

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#124]
ISSUE CONTENT
**URL:** 
https://givewp.com/documentation/core/settings/advanced/

**PROBLEM:** 
It's outdated and incomplete.

**SOLUTION:** 
1. Update settings language to match the actual plugin settings labels, i.e. "the_content filter" instead of "Disable the_content filter".
2. There's a stray hr, remove that
3. Add Akistmet SPAM Protection setting description.

**Comment by Benunc** [comment]
DONE.
