### ISSUE TITLE
UPDATE: Donors screen needs a screenshot and more detailed explanation

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#125]
ISSUE CONTENT
**URL:** 
https://givewp.com/documentation/core/donors/

**PROBLEM:** 
This screen lists all donors, it has 5 columns, and yet we don't have any screenshots or explanations for any of that.

It also has several sub-pages that are not in the right place at all.

**SOLUTION:** 
- [x] Model the format of this page according to the existing Donations page Doc:
https://givewp.com/documentation/core/donations/

1. General introduction to this screen
2. Screenshot of the screen
3. Explanation of each column and its action
    - Name
    - Email
    - Donations
    - Total Donated
    - Date Created

- [x] Re-order these sub-pages to be in this order:
* Donor Profile
* Donor Notes
* Delete Donor

- [x] Create a new page called "Managing Your Donors". That page would combine information from "Donor Tools", "Exporting Donors", and "Donor Reports" and then link to the associated existing docs on those tools and settings. Order that page to be last in this section. 

- [x] Delete the following pages:
* Donor Tools
* Exporting Donors
* Donor Reports

**Comment by Benunc** [comment]
Completed the first point here, today.

**Comment by Benunc** [comment]
In working on this, I found that the Data tab doc needed a screenshot. https://givewp.com/documentation/core/tools/data/

I added that just now, as well as the new Managing Donors page.

@mathetos I am unable to delete existing docs, but the three docs on the last step of this are OK to be deleted, then this can be closed.

**Comment by mathetos** [comment]
@Benunc I removed the other pages, but I think I didn't make it explicit that the "Delete Donor" page does not currently exist. So that needs to be done before this issue can be closed out.

**Comment by Benunc** [comment]
Done done.
