### ISSUE TITLE
[Give 2.0] "How to Add Custom Email Tags" deprecated

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#131]
ISSUE CONTENT
**URL:**
https://givewp.com/documentation/developers/how-to-add-custom-email-tags/

**PROBLEM:** 
Email tags callback now has array as argument instead of payment_id for better flexibility.
https://github.com/WordImpress/Give/commit/8d52b463ef26dc796d0511d5bdaece4aa49a74e6#commitcomment-26964661

**Comment by Benunc** [comment]
Have more users asking about this functionality. Is that snippet good to go, yet?

**Comment by samsmith89** [comment]
Confirmed that the snippet is functioning in local.
Updated the snippet.
Updated screenshot.
Updated note.
