### ISSUE TITLE
UPDATE: Improper grammar

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give-Docs#139]
**URL: ** https://givewp.com/documentation/core/requirements/

**PROBLEM:** "if you update an Add-on without updating Give Core what will happen is that you’ll see ~a~ _**an**_ admin notification"
**SOLUTION:** Replace alphabet **a** with the word **an**

**Comment by mathetos** [comment]
Yep, caught that while reviewing your other issue. Fixed. Thanks!
