### ISSUE TITLE
UPDATE: Improper sentence under "Floating Labels"

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give-Docs#141]
**URL:** https://givewp.com/documentation/core/give-forms/form-display/
**PROBLEM:** "Floating labels allows places your form’s input labels to be inside the input"
**SOLUTION:** It should say one of the following:

- Floating labels allow~s~ ~places~ your form’s input labels to be inside the input
- Floating labels ~allows~ places your form’s input labels to be inside the input

**Comment by marutim** [comment]
Fixed Now. Thanks @Sidsector9
