### ISSUE TITLE
New: {meta_*} email tag 

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#142]
## NECESSARY ITEMS
**User Story** 
As a Give Admin, I want to understand how to add any donor, donation, or form meta to my confirmation emails. I currently see a link the admin which leads nowhere. So I don't have any other discoverable method of understanding this powerful feature.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|Email Tags|*required* if its a new doc|
|**Current Url:**|https://givewp.com/documentation/core/settings/emails/email-tags|*required*|
|**Google Docs URL**|{Working on it}|*required* if creating a new doc

## ASSETS
We'll need some screenshots showing meta email tags in action.

## Related Give Core/Add-on issues

* https://github.com/WordImpress/Give/issues/2801#issuecomment-365136602

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] The link in the Give admin leads to the URL referenced above
- [x] The reader understands how email tags work generally
- [x] The reader understands how to create "meta" email tags
- [x] There are relevant screenshots to make the point more obvious

**Comment by mathetos** [comment]
@Benunc Can you review this doc please? Make necessary edits, and close when done. Thanks!

**Comment by Benunc** [comment]
Fantastic. I'm so pumped about this doc, and this feature.
