### ISSUE TITLE
web-doc(admin-setting): update Give Core > Payment Gateways

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#145]
## User Story

As a Give user, I want the `Enabled Gateways` documentation updated so that I understand how to customize payment gateways.

## Acceptance Criteria

- [x] I see an updated screenshot of the new `Enabled Gateways` UI in Give 2.1.
- [x] I understand how to customize gateway labels.
- [x] I understand how to enable/disable gateways.
- [x] I understand the meaning of `Default Gateway`.

### Screenshot of the new UI
![image](https://user-images.githubusercontent.com/1938671/38885469-022e085a-4241-11e8-8604-f01547b62992.png)

## Related

- https://givewp.com/documentation/core/payment-gateways/
- https://github.com/WordImpress/Give/issues/2429

**Comment by mathetos** [comment]
@samsmith89 Since this one is 100% about updating an existing doc, schedule to do the update on Tuesday next week, and just comment here when you publish the update and I'll review.

**Comment by samsmith89** [comment]
@mathetos This has been updated and is scheduled to post next Tuesday.

**Comment by samsmith89** [comment]
Need to redo this doc. Lost changes in the site.

**Comment by mathetos** [comment]
Here's Sam's doc for publishing:
https://docs.google.com/document/d/1dH1nT_T2T6Wx8C7tq2BeKOb7zG5HH7HFgcdDuhaziW8/edit

**Comment by samsmith89** [comment]
Changes Published:
https://givewp.com/documentation/core/payment-gateways/
