### ISSUE TITLE
New(cli): add documentation

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#146]
I did not fine Give CLI documentation on https://givewp.com/documentation/
Can we document it?

![image](https://user-images.githubusercontent.com/1784821/36801113-27b8434a-1cd7-11e8-91c8-2b6032b7a867.png)

**Comment by kevinwhoffman** [comment]
There is a blog post on Give CLI but it should probably be documented. https://givewp.com/command-line-support-coming-give-version-1-7/

**Comment by ravinderk** [comment]
@WordImpress/support note this change https://github.com/WordImpress/Give/issues/2845

**Comment by mathetos** [comment]
@Benunc Since you've been getting into WP CLI I think it'd be great for you to spend some time getting to know Give CLI and putting together an outline for this doc.

**Comment by Benunc** [comment]
Absolutely. I also want to put together a Give CLI wishlist. how cool would it be to be able to troubleshoot everything from the command line?

**Comment by DevinWalker** [comment]
@Benunc troubleshooting via command line is likely not going to be a possibility.  This is because customer's servers would have to be running WP-CLI because the Give CLI is built upon it. Only some of the managed hosts provide WP-CLI. Then you would need ssh access to the server, which is difficult in it's own right for some hosts because many require SSH keys and some don't even allow it.

**Comment by Benunc** [comment]
well, once I get a customer's site spun up locally, I can troubleshoot it with CLI. That's the main way I use WP_CLI at this point.

**Comment by Benunc** [comment]
began work on this today. 
https://givewp.com/wp-admin/post.php?post=260441&action=edit

**Comment by mathetos** [comment]
Good start @Benunc -- let's use the Public Preview links going forward (I edited your comment with that for now)

**Comment by Benunc** [comment]
More work on this today. here's the link for me to get right back to this tomorrow: https://givewp.com/wp-admin/post.php?post=260441&action=edit

**Comment by Benunc** [comment]
@ravinderk @Sidsector9 for the `wp give reports --start-date` parameter, what format should i use for the date? I used 01012018 for January 01 2018, and it isn't working. Trying to figure out what I'm doing wrong here.

**Comment by Benunc** [comment]
Other than the above clarification from the team, this doc is ready to ship. @mathetos let's interface on the content of the video for this one. Other than that, it's ready to go.

**Comment by ravinderk** [comment]
![image](https://user-images.githubusercontent.com/1784821/39030053-fe98b90e-447c-11e8-95cb-ecfe53859f20.png)

@Benunc We already have dummy queries in the example. If you only enter `--start-date` then you will date donation stats only for that day, so be specific about what are you entering in `--start-date` and `--end-date` 

commit: https://github.com/WordImpress/Give/compare/43f89ead7d00...7caa4a340b0d

**Comment by Benunc** [comment]
Updated the doc with the insight from Ravinder above and this issue is DONE.
