### ISSUE TITLE
Update: recurring addon screenshots

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#147]
ISSUE CONTENT
@mathetos I think recurring addon screenshot deprecated. Please review them.

https://givewp.com/addons/recurring-donations/

**Comment by marutim** [comment]
@mathetos I do not have access to edit this page https://givewp.com/addons/recurring-donations/ so instead, I am going through all the documentation for recurring donation and checking for outdated content or screenshots.

**Comment by marutim** [comment]
Reviewed the following docs:
https://givewp.com/documentation/add-ons/recurring-donations/recurring-emails/
https://givewp.com/documentation/add-ons/recurring-donations/managing-subscriptions/
https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/

Will continue with the rest tomorrow

**Comment by marutim** [comment]
Reviewed res of the docs
https://givewp.com/documentation/add-ons/recurring-donations/renewal-donation-reports/
https://givewp.com/documentation/add-ons/recurring-donations/subscription-transaction-statuses/
https://givewp.com/documentation/add-ons/recurring-donations/faq/
https://givewp.com/documentation/add-ons/recurring-donations/testing-recurring/

Assigning it to Matt for review.

**Comment by mathetos** [comment]
Looks good @marutim THanks!
