### ISSUE TITLE
UPDATE: Path to display custom taxonomies

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give-Docs#149]
**URL:** https://givewp.com/using-categories-tags-give/

**PROBLEM:** Currently it says "navigate to Donations > Settings > Display Options and enable them by checking the boxes and saving the settings."

**SOLUTION:** Rather it should say "navigate to Donations > Settings > Display Options > **Taxonomies** and enable them by checking the boxes and saving the settings."

**Comment by marutim** [comment]
@Benunc I don't have access to edit this page so assigned it to you.

**Comment by Benunc** [comment]
Done!
