### ISSUE TITLE
UPDATE: Type on Give's API documentation page

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give-Docs#150]
ISSUE CONTENT
**URL:** https://givewp.com/documentation/developers/give-api-reference/

**PROBLEM:** Statement reads - "Did you know that Give comes packaged with a powerful API that allows **_your_** to expose donation data in either JSON."

**SOLUTION:** Change "your" to "you"

**Comment by kevinwhoffman** [comment]
Fixed. Thanks @Sidsector9.
