### ISSUE TITLE
UPDATE: Typo on Give's frequent troubleshooting page

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give-Docs#151]
ISSUE CONTENT
**URL**: https://givewp.com/documentation/core/frequent-troubleshooting-issues/admin-ajax-blocked/

**PROBLEM**: Statement reads - " Give cannot access it then you may see **an** notice or experience various errors."

**SOLUTION**: Change "an" to "a"

**Comment by marutim** [comment]
Thanks for reporting that @Sidsector9. Fixed now :)
