### ISSUE TITLE
web-doc(shortcode): Add new [give_totals] doc for Give 2.1.0 release

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Docs#152]
**URL:** https://givewp.com/documentation/core/shortcodes/give_totals/

**PROBLEM:** There is a new `[give_totals]` shortcode releasing in Give 2.1.0 with no documentation.

**SOLUTION:** Document the shortcode and its attributes, with a screenshot of the shortcode generator.

- Original issue: https://github.com/WordImpress/Give/issues/1472
- Code: The new shortcode has been merged to the 2.1.0 branch: https://github.com/WordImpress/Give/blob/issue/2943/includes/shortcodes.php#L548-L692

**Comment by samsmith89** [comment]
Saved as Draft and ready for 2.1 release
https://givewp.com/documentation/core/shortcodes/give_totals/

**Comment by mathetos** [comment]
@Benunc Please review the draft as soon as you can. Let's close when it's published.

**Comment by samsmith89** [comment]
Published at:
https://givewp.com/documentation/core/shortcodes/give_totals/
