### ISSUE TITLE
NEW: Add Give Cache setting doc for Give 2.1.0 release

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#153]
PROBLEM: There is a new `Give Cache` admin setting is releasing in `Give` 2.1.0 with no documentation.

SOLUTION: Document the admin setting.
https://github.com/WordImpress/Give/issues/2719

**Comment by marutim** [comment]
Worked on this on a Google doc here: https://docs.google.com/document/d/1wbWp712_HgVSwzApaErUZY3ZP-3yIbVq2RhW48IikWc/

@mathetos You can review it now.

**Comment by mathetos** [comment]
@marutim I made minor tweaks/additions. When we launch 2.1 this content will be added to this existing doc:
https://givewp.com/documentation/core/settings/advanced/

Just make sure it's in the right place within that doc based on how it appears in the plugin itself.

**Comment by marutim** [comment]
OKay Matt

**Comment by mathetos** [comment]
Looks great, thanks!
