### ISSUE TITLE
NEW: Donation Form Grid

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#155]
ISSUE CONTENT
**URL:** 
https://givewp.com/documentation/core/shortcodes/give_form_grid

**PROBLEM:** 
This is a new feature in Give 2.1 and it is not yet documented.

**SOLUTION:** 
- [x] Create the doc at the URL above.
- [x] Make sure that doc describes each attribute of the shortcode following the format used on this page:
- [x] Include a screenshot of the shortcode builder using this shortcode 

**RELATED ISSUES**
* Form Grid Give Core Issue: https://github.com/WordImpress/Give/issues/2943

**Comment by samsmith89** [comment]
Ready for review.

**Comment by mathetos** [comment]
Here's the link:
https://givewp.com/?post_type=documentation&p=257545&preview=true

**Comment by Benunc** [comment]
@samsmith89 can you ensure that the new issue #162 is addressed for this doc? closing this in favor of that.
