### ISSUE TITLE
UPDATE: Move CSV Toolbox docs to Give core Export docs

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Docs#157]
**URL:**
https://givewp.com/documentation/core/tools/exports-tab/
https://givewp.com/documentation/add-ons/form-field-manager/give-csv-toolbox/

**PROBLEM:** CSV Toolbox is being merged into Give core in version 2.1.0. It will be accessible from the Tools > Export tab. It will be the default UI for exporting Donation History–making it much more powerful than our existing Donation History export.

See the video in this comment for more info: https://github.com/WordImpress/Give/issues/2875#issuecomment-377362329

**SOLUTION:**
- [ ] Update the Export docs to cover the CSV toolbox UI
- [ ] Update the Export docs screenshots
- [ ] Remove CSV Toolbox docs as everything there will be covered in the Give core Export docs

**Comment by samsmith89** [comment]
When testing this feature in 2.1 I was unable to make the Form Field Manager custom fields display.

**Comment by mathetos** [comment]
Here's @samsmith89 s draft doc:
https://docs.google.com/document/d/1dH1nT_T2T6Wx8C7tq2BeKOb7zG5HH7HFgcdDuhaziW8/edit

**Comment by samsmith89** [comment]
Changes are published:
https://givewp.com/documentation/core/tools/exports-tab/
