### ISSUE TITLE
UPDATE: Typo on Give Recurring Docs

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give-Docs#160]
ALL ISSUES SHOULD FOLLOW THIS FORMAT:

ISSUE CONTENT
**URL:** https://givewp.com/documentation/add-ons/recurring-donations/getting-started/

**PROBLEM:**  Card data is never **store** on your site.

**SOLUTION:** It should be **stored**.

**Comment by marutim** [comment]
good catch @Sidsector9. This is fixed now
