### ISSUE TITLE
UPDATE: Typo on Give Recurring Documentation

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give-Docs#161]
**URL:** https://givewp.com/documentation/add-ons/recurring-donations/recurring-emails/

**PROBLEM:** It says "notify your donors when their subscriptions renewed".

**SOLUTION:** It should be "notify your donors when their subscriptions **renew**" OR "notify your donors when their subscriptions **are** renewed"

**Comment by marutim** [comment]
Thanks @Sidsector9.
