### ISSUE TITLE
web-doc(shortcode): update [give_form_grid] doc

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Docs#162]
## User Story

As an author, I want to see an up-to-date version of the `[give_form_grid]` shortcode generator so that the documentation matches what I see on screen.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/core/shortcodes/give_form_grid/|*required*|

## Assets

Development in progress in https://github.com/WordImpress/Give/issues/3147. Screenshot will be available after merge.

## Acceptance Criteria

- [x] I see an up-to-date screenshot of the shortcode generator and its options.
- [x] I understand that the `columns` option defaults to `best-fit`, which means the grid will automatically adjust the number of columns based on the available space.
- [x] I understand that `forms_per_page` defaults to 12 forms, and pagination controls will be visible if more than the specified number of forms exist.
- [x] I understand that `ids` is empty by default and queries all forms by date. Providing a comma-separated list of IDs will cause the grid to include only those forms.

## Related

https://github.com/WordImpress/Give/issues/3147

**Comment by samsmith89** [comment]
Updated the Doc with the necessary additions.

**Comment by Benunc** [comment]
Great work. Closing.
