### ISSUE TITLE
web-doc: update recommended method to apply custom CSS

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Docs#163]
**User Story** 

As a developer who wants to customize Give styles, I want to know the modern approach to add custom CSS in WordPress so that it does not get lost in future updates.

The existing doc contains outdated recommendations of third-party plugins that may not be necessary since the Customizer now supports Additional CSS.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/resources/handling-custom-css-in-wordpress/|*required*|
|**Google Docs URL**|TBD|*required* if creating a new doc

## Assets

- Should include a screenshot of the Additional CSS panel in the Customizer.

## Related Give Core/Add-on issues

This user edited our minified styles within the plugin and doesn't understand why those changes were lost on update.

https://wordpress.org/support/topic/css-not-applying-since-update/

## Acceptance Criteria

- [ ] I understand that editing the Give plugin's CSS is not an option as changes will get lost in the next update.
- [ ] I understand how to find the Additional CSS panel in the customizer to add my styles.
- [ ] I understand that Additional CSS may be lost if the theme changes, and that a plugin solution like [Modular Custom CSS](https://wordpress.org/plugins/modular-custom-css/) is required in order to preserve styles after theme changes.

**Comment by mathetos** [comment]
Thanks @kevinwhoffman This has been in the back of my mind for over a year -- I needed this kick in the pants. It's been basically re-written now and updated. Thanks!
