### ISSUE TITLE
web-doc(give-authorize): Explain process of setting up eCheck

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give-Docs#167]
## Necessary Items
**User Story** 
Describe what the user wants in regard to this doc in these terms:
As a site admin, I want to know how to set up eCheck so that I don't have to go searching through Authorize.net for basic information.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/add-ons/authorize-net-gateway/|*required*|

## Acceptance Criteria
List what will make this doc ready to publish. Example:

**This doc is ready to publish when:**
- [ ] There's an updated screenshot signifying eCheck is available.
- [x] Walk the user through the process of applying for eCheck functionality.
- [x] User understands there are fee's associated.
- [x] User know where to get additional information.

**Comment by samsmith89** [comment]
**Content of the Doc:**

<h3>Authorize eCheck ACH payments</h3>

Give allows your donors to make their donations using Authorize.net eCheck. eCheck is an ACH transaction that takes the donor's bank account information to process the transaction. This account comes with a lower per-transaction fee, but you need to be aware of some additional items in order to get set up.

First, we are going to need to apply to Authorize.net for the ability to use eCheck. Once you have received confirmation and eCheck is turned on in your Merchant Account, you will be all set.

There are other fees associated with eCheck, these include: 

- There is a one-time setup fee for existing Payment Gateway customers.
- Per transaction percentage fee.
- Minimum monthly fee. 

Here is a link to their fee structure. 
https://www.authorize.net/solutions/merchantsolutions/merchantservices/echeck/

To set up eCheck in Give, navigate to Donations >> Settings >> Payment Gateways. Then enable the Authorize.net eCheck (ACH). There is nothing else you will need to enable in the backend of Give as long as your account is set up to handle eCheck transactions. 

Here is a testing guide for processing test payments with eCheck:
https://developer.authorize.net/hello_world/testing_guide/

**Comment by mathetos** [comment]
Great work @samsmith89 I published this here:
https://givewp.com/documentation/add-ons/authorize-net-gateway/configuring-echeck/
