### ISSUE TITLE
web-doc(admin-email): update Email Notifications doc with new tags

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Docs#178]
**User Story** 
As a user, I want to be aware of the following email tags coming to Give 2.2.0 so that I understand where they are defined and used.

1. `{admin_email}`
2. `{offline_mailing_address}`
3. `{site_url}`

These three tags will provide a major convenience to developers who migrate sites from dev to production since they will only have to update this information in one place as opposed to every email template.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/core/give-forms/email-notifications/|*required*|

## Assets

[Sid's video](https://www.useloom.com/share/d9756dd20a874037bd9a15c8fa17c78c) does a very good job of explaining the new tags and the convenience they offer.

## Related Give Core/Add-on issues

https://github.com/WordImpress/Give/pull/3378

## Acceptance Criteria

- [x] I see each of the three new tags in the full tags list that appears halfway down the page.
- [x] I understand where in the settings I should go to update the value of these tags.

**Comment by marutim** [comment]
Link to the doc: https://docs.google.com/document/d/1A19mxydYBlPpp-fS9eL4vFhSWKCe-85Q6zybUFc-F6w

@mathetos Can you review and let me know if this is okay or should I add more details to this.

I followed the explanation of email tags in this page here: https://givewp.com/documentation/core/give-forms/email-notifications/

**Comment by Benunc** [comment]
I modified @marutim's content, simplified it, added it to the doc, and published. This is closed now. Thanks!
