### ISSUE TITLE
web-doc(give_form_grid): Fix the typos

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give-Docs#180]
## Necessary Items
**User Story** 
This doc has couple of typos that I have highlighted in the screenshots below.

**Doc Details**

|**Current Url:**|https://givewp.com/documentation/core/shortcodes/give_form_grid/|

## Assets
![image](https://user-images.githubusercontent.com/3498917/42092091-4f74c014-7bc5-11e8-943a-3c69de0a964c.png)
![image](https://user-images.githubusercontent.com/3498917/42092109-5c16dbe0-7bc5-11e8-8053-8601aa2b380e.png)

**Comment by telizarose** [comment]
Updated. Thanks!
