### ISSUE TITLE
web-doc(give-core): Add doc about restoring your site when a plugin whitescreens your site

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#185]
## Necessary Items
**User Story** 
As a Give user I want to rely on the Give team to provide me with solutions, particularly ones that occur when a Give Addon whitescreens my site. I don't want to have to read a tutorial somewhere else.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|How to Deactivate WordPress plugins when you can't access your site. |*required*|
|**New Url:**|https://givewp.com/documentation/resources/deactivate-wordpress-plugins-white-screen|*required* |
|**Google Docs URL**|TBD|*required* |

## Acceptance Criteria
When I read this doc, I leave understanding how to: 
- [ ] get and use an FTP client
- [ ] use an FTP client to access my website
- [ ] use my FTP client to deactivate one plugin by changing the folder name
- [ ] confirm that my site is active and the plugin is deactivated correctly
- [ ] revert the plugin namechange
- [ ] contact support about the problematic plugin

Additionally, this doc needs to have the following as well:
- [ ] ample screenshots to highlight each step
- [ ] Perhaps a video overview
- [ ] @telizarose should do some SEO-tweaks to get good search engine results

**Comment by samsmith89** [comment]
Here is the Doc link:
https://docs.google.com/document/d/1MMJ1W7htymnxQUQcqmQTmY6tQwgmrMX2XQWCyLOIC_M/edit?usp=sharing

**Comment by samsmith89** [comment]
Text finished for the post at the link above. Just need to get in screenshots. Let me know of any feedback.

**Comment by samsmith89** [comment]
Ready to publish. Just need feedback

**Comment by samsmith89** [comment]
Changed it after receiving feedback and published.
