### ISSUE TITLE
[Give 2.2.1] Update: email template tag registration API

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Docs#187]
You can pass an array of arguments to register email template tag and also added `is_admin`
param which will check if we have to hide particular tag on email edit screen or not.
Check code sample in PR description: https://github.com/WordImpress/Give/pull/3528

Issue link: https://github.com/WordImpress/Give/issues/3516

**Comment by DevinWalker** [comment]
@ravinderk can you link to the doc that needs to be updated and screenshot the outdated code?

**Comment by ravinderk** [comment]
Link of doc: https://givewp.com/documentation/developers/how-to-add-custom-email-tags/

**Comment by DevinWalker** [comment]
@ravinderk I have updated the doc
