### ISSUE TITLE
NEW: Testing Authorize.net

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Docs#75]
ISSUE CONTENT
**URL:** 
https://givewp.com/documentation/add-ons/authorize-net-gateway/testing -- needs to be created

**PROBLEM:** 
Testing Authorize.net with Give in Test Mode is important, but requires special steps to make happen well. 

**SOLUTION:** 
We need to add this page to address it head-on.

Here's the outline that this doc should follow:

1. Introduce the purpose of the article, similar to how we introduce it in the "Testing Stripe" section here: https://givewp.com/documentation/add-ons/stripe-gateway/ and make sure to reference and link to Give's Test Mode feature.

2. Creating an Authorize.net Sandbox Account

3. Finding your Sandbox API Keys for use in Give

4. Where to find Authorize Test credit card numbers

5. Test for success, failure, and required fields

**Comment by mathetos** [comment]
@Benunc I just assigned this to you and am re-opening. We never published this doc. It should be made live here:
https://givewp.com/documentation/add-ons/authorize-net-gateway/testing

**Comment by mathetos** [comment]
Testing Slack Github integration for duplicate notifications

**Comment by mathetos** [comment]
One more test...

**Comment by mathetos** [comment]
Last test... really.

**Comment by Benunc** [comment]
done https://givewp.com/documentation/add-ons/authorize-net-gateway/testing-authorize-net/
